<?php
session_start();

// Check if user is logged in and 2FA verified
if (!isset($_SESSION['logged_in']) || $_SESSION['logged_in'] !== true || 
    !isset($_SESSION['2fa_verified']) || $_SESSION['2fa_verified'] !== true) {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Unauthorized access']);
    exit();
}

// Include connection
include '../connection.php';

// Check if connection is successful
if (!$db) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Database connection failed']);
    exit();
}

// Function to perform database backup
function backupDatabase($db) {
    // Get all table names
    $tables = array();
    $result = $db->query("SHOW TABLES");
    while ($row = $result->fetch_row()) {
        $tables[] = $row[0];
    }
    
    // Create backup content in memory
    $backup_content = "";
    
    // Add header information
    $backup_content .= "-- Database Backup: " . date('Y-m-d H:i:s') . "\n";
    $backup_content .= "-- Generated by RFIDGPMS System\n\n";
    
    // Process each table
    foreach ($tables as $table) {
        $backup_content .= "-- Table structure for table `$table`\n";
        $backup_content .= "DROP TABLE IF EXISTS `$table`;\n\n";
        
        // Get table structure
        $result = $db->query("SHOW CREATE TABLE `$table`");
        $row = $result->fetch_row();
        $backup_content .= $row[1] . ";\n\n";
        
        // Get table data
        $result = $db->query("SELECT * FROM `$table`");
        $num_fields = $result->field_count;
        $num_rows = $result->num_rows;
        
        if ($num_rows > 0) {
            $backup_content .= "-- Dumping data for table `$table`\n";
            
            while ($row = $result->fetch_row()) {
                $backup_content .= "INSERT INTO `$table` VALUES (";
                
                $values = array();
                for ($j = 0; $j < $num_fields; $j++) {
                    $value = $row[$j];
                    
                    if ($value === null) {
                        $values[] = 'NULL';
                    } else {
                        $value = addslashes($value);
                        $value = str_replace("\n", "\\n", $value);
                        $value = str_replace("\r", "\\r", $value);
                        $value = str_replace("\t", "\\t", $value);
                        $values[] = '"' . $value . '"';
                    }
                }
                
                $backup_content .= implode(', ', $values);
                $backup_content .= ");\n";
            }
            
            $backup_content .= "\n\n";
        }
    }
    
    return $backup_content;
}

// Handle the backup request
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    try {
        // Perform backup
        $backup_content = backupDatabase($db);
        
        // Generate filename
        $filename = 'backup_' . date('Y-m-d_H-i-s') . '.sql';
        
        // Set headers for direct download
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($backup_content));
        header('Cache-Control: no-cache, must-revalidate');
        header('Pragma: no-cache');
        header('Expires: 0');
        
        // Output the backup content
        echo $backup_content;
        exit;
        
    } catch (Exception $e) {
        // Return error
        http_response_code(500);
        header('Content-Type: application/json');
        echo json_encode([
            'success' => false,
            'message' => 'Backup failed: ' . $e->getMessage()
        ]);
        exit;
    }
}

// If not GET request, return error
http_response_code(405);
echo json_encode(['success' => false, 'message' => 'Method not allowed']);
exit;
?>